# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python tests

on:
  workflow_dispatch: # Trigger the workflow manually
    inputs:
      tags: # Input parameter for test scenario tags
        description: "Test scenario tags"
        required: true
        default: "shady_meadow_ui"

jobs:
  generate-allure-report:
    runs-on: ubuntu-latest 

    # defaults:
    #   run:
    #     shell: bash # Set the shell for the job
    #     working-directory: ./test # Set the working directory for the job

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: browser-actions/setup-chrome@v1
      - run: chrome --version

      - name: Install Python 
        uses: actions/setup-python@v5
        with:
          python-version: 3.11 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # - name: Install dependencies 
      #   run: |
      #     python -m pip install --upgrade pip
      #     python3 -m venv my_venv
      #     source ./my_venv/bin/activate
      #     pip install -r requirements.txt

      - run: mkdir -p ./results
      - run: echo hello > ./results/report.html

      - name: Test with pytest
        run: |
          pytest --html=results/report.html --self-contained-html

      - uses: actions/upload-artifact@v4
        with:
          name: report
          path: ./results/report.html
          


     
      # - name: Load test report history
      #   uses: actions/checkout@v4
      #   if: always()
      #   continue-on-error: true
      #   with:
      #     ref: ShadyMeadowsBedAndBreakfast
      #     path: ShadyMeadowsBedAndBreakfast

      # - name: Build test report
      #   uses: simple-elf/allure-report-action@v1.7
      #   if: always()
      #   with:
      #     github_repo: ShadyMeadowsBedAndBreakfast
      #     allure_history: allure-history
      #     allure_results: build/allure-results

      # - name: Publish test report
      #   uses: peaceiris/actions-gh-pages@v4
      #   if: always()
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_branch: ShadyMeadowsBedAndBreakfast
      #     publish_dir: allure-history
      

